---
  - name: Install dependencies wordpress
    ansible.builtin.apt:
      pkg:
      - apache2 
      - ghostscript 
      - libapache2-mod-php 
      - php 
      - php-mysql
      - php-bcmath 
      - php-curl 
      - php-imagick 
      - php-intl 
      - php-json 
      - php-mbstring 
      - php-xml 
      - php-zip
      state: latest
      update_cache: yes
    become: yes